ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
PHYSICS_SIMULATOR:
  TYPE: "Sim-v2"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ENABLE_PHYSICS: True
  RGB_SENSOR:
    WIDTH: 720
    HEIGHT: 720
  DEPTH_SENSOR:
    WIDTH: 720
    HEIGHT: 720
TASK:
  TYPE: Nav-v1
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

